library(readxl)
library(dplyr)
library(ggplot2)
data <- read_excel("data.xlsx")
data <- data %>% mutate(`Interaction Date` = as.Date(`Interaction Date`))
data <- data %>% filter(`Method of Communication` == "Site Visit")
data <- data %>% count(month = format(`Interaction Date`,"%Y-%m"))
data$month <- as.Date(paste0(data$month, "-01"))
ggplot(data, aes(x=month,y=n)) + geom_line() + geom_smooth(method="lm",se=FALSE)
model <- lm(n ~ month, data)
summary(model)
